# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"
  build_info = true
  extra_output = ["storageLayout"]
  fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
  ]
  
[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  arbitrum = { key = "${API_KEY_ARBISCAN}" }
  arbitrum_sepolia = { key = "${API_KEY_ARBISCAN}" }
  avalanche = { key = "${API_KEY_SNOWTRACE}" }
  goerli = { key = "${API_KEY_ETHERSCAN}" }
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  optimism_sepolia = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  base = { key = "${API_KEY_BASE}" }
  base_sepolia = { key = "${API_KEY_BASE}" }
  bera_testnet = { key = "${API_KEY_BERA}" }
  

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  arbitrum_sepolia = "${ARB_SEPOLIA_RPC}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  goerli = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_GOERLI}"
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  optimism = "https://opt-mainnet.g.alchemy.com/v2/${API_KEY_OPTIMISTIC}"
  optimism_sepolia = "https://opt-sepolia.g.alchemy.com/v2/${API_KEY_OPTIMISTIC_SEPOLIA}"
  polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
  sepolia = "https://rpc.ankr.com/eth_sepolia"
  phi = "https://rpc-test-ph-uop5quepc8.t.conduit.xyz"
  orbit_test = "https://orbit-demo.alt.technology"
  base = "${BASE_MAINNET_RPC}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_BASE_SEPOLIA}"
  syndicate = "https://rpc-frame.syndicate.io"
  bera_testnet = "https://bitter-rough-owl.bera-bartio.quiknode.pro/4e2fcb78f8ac6cd2d04e471385cb875623f4c57a"
  zora_sepolia = "${ZORA_SEPOLIA_RPC}"
  cyber_testnet = "https://cyber-testnet.alt.technology/"
  cyber = "https://cyber.alt.technology/"
